### ISSUE TITLE
Connection is never closed  by napalm_configure

### ISSUE THREAD

**Issue by lamehost** [nornir-automation/nornir_napalm#34]
Dear maintaners,

I am developing a Nornir based application that pushes configuration to IOS-XR devices via `napalm_configure` and i've noticed that - from time to time - all of the VTYs on the devices in my testing environment get consumed.

While investigating, i have noticed that [a connection to the device is open by napalm_configure](https://github.com/nornir-automation/nornir_napalm/blob/master/nornir_napalm/plugins/tasks/napalm_configure.py#L30), but it is never closed (at least not by this plugin)

So, If i am understanding it correctly, then it is up to the device to close connection. While it would be smarter it the client would do so.
It would be quite and easy change to make within `napalm_configure`. But i am not 100% sure if that's the right point or if a connection should be closed elsewhere.

Would you mind to explain?

Thank you

Regards

**Comment by ktbyers** [comment]
@lamehost Have you checked at the NAPALM for IOS-XR (it is not clear from the question whether you are using the ios-xr napalm driver that uses `xml-agent` or the `netconf` driver) and whether it is properly closing the connection on the `.close()` call?

**Comment by lamehost** [comment]
@dbarrosop 
I've read that page, but i can't find where the connection is closed by Nornir. Where is it? Would you be so kind to tell?

@ktbyers 
I am using the `xml-agent` one

**Comment by dbarrosop** [comment]
It is handled by nornir automagically unless you decide to manage the connection yourself explicitly. When exactly doesn't really matter (but for the sake of completion, it happens when the object is garbage collected), the point is that if you need to open/close the connection at specific times you can do it already.

Re-reading your issue, I am a bit confused though. Nornir only opens [one connection per device and connection type](https://github.com/nornir-automation/nornir/blob/main/nornir/core/inventory.py#L475-L504) so I am unsure how nornir could be exhausting your VTYs. Have you checked with IOS-XR that that the VTYs are, in fact, being used by nornir? If yes, could you share the simplest script that triggers the issue?
